"use client";

import { ArrowDownRight, ArrowUpRight, ChevronRight, CreditCard, MoreHorizontal, Sparkles, TrendingUp, WalletCards } from "lucide-react";
import Link from "next/link";
import { money, totals, useFinance } from "./finance-store";
import { Pill } from "./ui";

export function BalanceCard() { const { transactions } = useFinance(); const { balance, income, expenses } = totals(transactions); return <section className="lift relative overflow-hidden rounded-[24px] bg-forest p-5 text-white shadow-lg shadow-forest/15 sm:p-6"><div className="absolute -right-16 -top-16 h-48 w-48 rounded-full border border-white/10"/><div className="absolute right-8 top-12 h-24 w-24 rounded-full border border-white/10"/><div className="relative"><div className="flex items-center justify-between"><p className="text-[11px] font-semibold tracking-[.13em] text-soft-sage">THIS MONTH&apos;S BALANCE</p><WalletCards size={20} className="text-sage"/></div><p className="font-finance mt-5 text-[30px] font-semibold tracking-[-.07em] sm:text-4xl">{money(balance)}</p><div className="mt-6 flex flex-wrap gap-2"><Pill>+ {money(income)} income</Pill><Pill>− {money(expenses)} expenses</Pill></div></div></section>; }
export function FinancialSummary() { const { transactions } = useFinance(); const { income, expenses, saved } = totals(transactions); const rate = income ? Math.round((saved / income) * 100) : 0; const summary = [{ label: "Income", value: money(income), icon: ArrowDownRight, bg: "bg-soft-sage", color: "text-green" }, { label: "Expenses", value: money(expenses), icon: ArrowUpRight, bg: "bg-[#F3E8E2]", color: "text-[#8E503B]" }, { label: "Saved", value: `${rate}%`, icon: TrendingUp, bg: "bg-[#E7EFF7]", color: "text-[#42617B]" }]; return <section aria-label="Monthly financial summary" className="grid grid-cols-3 gap-2.5">{summary.map(({ label, value, icon: Icon, bg, color }) => <article key={label} className="rounded-2xl border border-line bg-white p-3"><span className={`grid h-7 w-7 place-items-center rounded-lg ${bg} ${color}`}><Icon size={15}/></span><p className="mt-3 text-[10px] font-medium text-muted">{label}</p><p className="font-finance mt-1 truncate text-[13px] font-semibold text-ink sm:text-sm">{value}</p></article>)}</section>; }
export function AIFinancialBrief() { const { transactions } = useFinance(); const { income, expenses } = totals(transactions); const rate = income ? Math.round((expenses / income) * 100) : 0; return <section className="rounded-[22px] border border-[#B8D0C8] bg-soft-sage p-4"><div className="flex gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-green text-white"><Sparkles size={18}/></span><div><div className="flex items-center gap-2"><p className="text-[11px] font-bold tracking-[.1em] text-green">MONEY SNAPSHOT</p><span className="rounded-full bg-white/70 px-2 py-0.5 text-[9px] font-semibold text-green">Local</span></div><p className="mt-2 text-[13px] leading-5 text-[#315A50]">You&apos;ve used {rate}% of the income you&apos;ve recorded this month. Keep an eye on your everyday spending.</p><Link href="/analytics" className="mt-2 flex min-h-7 items-center gap-1 text-xs font-semibold text-green">See breakdown <ChevronRight size={14}/></Link></div></div></section>; }
export function MonthlyOverview() { const { transactions } = useFinance(); const { expenses } = totals(transactions); const days = [23, 41, 30, 58, 45, 76, 52, 66]; return <section className="rounded-[22px] border border-line bg-white p-4"><div className="flex items-center justify-between"><div><p className="font-display text-base font-semibold text-ink">Monthly overview</p><p className="mt-0.5 text-xs text-muted">Your spending activity</p></div><button aria-label="More monthly overview options" className="grid h-9 w-9 place-items-center rounded-full text-muted hover:bg-canvas"><MoreHorizontal size={20}/></button></div><div className="mt-5 flex h-20 items-end justify-between gap-2">{days.map((height, index) => <div key={index} className="flex flex-1 flex-col items-center gap-1"><div className={`w-full max-w-5 rounded-full ${index === 5 ? "bg-green" : "bg-soft-sage"}`} style={{ height: `${height}%` }}/>{index === 5 && <span className="text-[9px] font-semibold text-green">F</span>}</div>)}</div><div className="mt-4 flex items-center justify-between border-t border-line pt-3 text-xs"><span className="text-muted">Recorded expenses</span><span className="font-finance font-medium text-green">{money(expenses)}</span></div></section>; }
const categoryStyle: Record<string, string> = { Groceries: "bg-[#F5ECE5] text-[#8D593E]", Transport: "bg-[#E9F0E9] text-[#35704D]", Income: "bg-soft-sage text-green", "Food & drink": "bg-[#F7EAF0] text-[#97506D]", Subscriptions: "bg-[#E7EFF7] text-[#42617B]" };
export function RecentTransactions() { const { transactions } = useFinance(); return <section><div className="flex items-center justify-between"><div><p className="font-display text-base font-semibold text-ink">Recent transactions</p><p className="mt-0.5 text-xs text-muted">Your latest activity</p></div><Link href="/transactions" className="flex min-h-10 items-center gap-0.5 text-xs font-semibold text-green">View all <ChevronRight size={15}/></Link></div><div className="mt-3 divide-y divide-line overflow-hidden rounded-[22px] border border-line bg-white">{transactions.slice(0, 3).map((transaction) => <div key={transaction.id} className="flex items-center gap-3 p-3.5"><span className={`grid h-9 w-9 place-items-center rounded-xl ${categoryStyle[transaction.category] ?? "bg-canvas text-muted"}`}><CreditCard size={17}/></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-ink">{transaction.name}</p><p className="mt-0.5 text-xs text-muted">{transaction.category} · {new Date(`${transaction.date}T00:00:00`).toLocaleDateString("en-MY", { day: "numeric", month: "short" })}</p></div><p className={`font-finance text-xs font-medium ${transaction.type === "income" ? "text-green" : "text-ink"}`}>{transaction.type === "income" ? "+ " : "− "}{money(transaction.amount)}</p></div>)}</div></section>; }
export function BudgetAlert() { const { transactions, budgets } = useFinance(); const spending = transactions.filter((item) => item.type === "expense").reduce<Record<string, number>>((all, item) => ({ ...all, [item.category]: (all[item.category] ?? 0) + item.amount }), {}); const alert = budgets.map((budget) => ({ ...budget, used: spending[budget.category] ?? 0 })).find((budget) => budget.used >= budget.limit * 0.8); if (!alert) return null; const over = alert.used > alert.limit; return <Link href="/analytics" className={`block rounded-[20px] border p-4 ${over ? "border-[#E8BBB0] bg-[#FBEDE9]" : "border-[#B8D0C8] bg-soft-sage"}`}><p className={`text-xs font-bold tracking-[.08em] ${over ? "text-[#A33F2D]" : "text-green"}`}>{over ? "BUDGET ALERT" : "BUDGET CHECK-IN"}</p><p className="mt-1 text-sm text-ink">{over ? `${alert.category} is over its RM ${alert.limit.toFixed(0)} budget.` : `${alert.category} has reached ${Math.round((alert.used / alert.limit) * 100)}% of its monthly budget.`}</p></Link>; }
