"use client";

import { useMemo, useState } from "react";
import { ArrowDownRight, ArrowUpRight, ChevronRight, CreditCard, Sparkles, TrendingUp, WalletCards } from "lucide-react";
import Link from "next/link";
import { money, totals, useFinance } from "./finance-store";
import { Pill } from "./ui";

export function BalanceCard() { const { transactions } = useFinance(); const { balance, income, expenses } = totals(transactions); return <section className="lift relative overflow-hidden rounded-[24px] bg-forest p-5 text-white shadow-lg shadow-forest/15 sm:p-6"><div className="absolute -right-16 -top-16 h-48 w-48 rounded-full border border-white/10"/><div className="absolute right-8 top-12 h-24 w-24 rounded-full border border-white/10"/><div className="relative"><div className="flex items-center justify-between"><p className="text-[11px] font-semibold tracking-[.13em] text-soft-sage">THIS MONTH&apos;S BALANCE</p><WalletCards size={20} className="text-sage"/></div><p className="font-finance mt-5 text-[30px] font-semibold tracking-[-.07em] sm:text-4xl">{money(balance)}</p><div className="mt-6 flex flex-wrap gap-2"><Pill>+ {money(income)} income</Pill><Pill>− {money(expenses)} expenses</Pill></div></div></section>; }
export function FinancialSummary() { const { transactions } = useFinance(); const { income, expenses, saved } = totals(transactions); const rate = income ? Math.round((saved / income) * 100) : 0; const summary = [{ label: "Income", value: money(income), icon: ArrowDownRight, bg: "bg-soft-sage", color: "text-green" }, { label: "Expenses", value: money(expenses), icon: ArrowUpRight, bg: "bg-[#F3E8E2]", color: "text-[#8E503B]" }, { label: "Saved", value: `${rate}%`, icon: TrendingUp, bg: "bg-[#E7EFF7]", color: "text-[#42617B]" }]; return <section aria-label="Monthly financial summary" className="grid grid-cols-3 gap-2.5">{summary.map(({ label, value, icon: Icon, bg, color }) => <article key={label} className="rounded-2xl border border-line bg-white p-3"><span className={`grid h-7 w-7 place-items-center rounded-lg ${bg} ${color}`}><Icon size={15}/></span><p className="mt-3 text-[10px] font-medium text-muted">{label}</p><p className="font-finance mt-1 truncate text-[13px] font-semibold text-ink sm:text-sm">{value}</p></article>)}</section>; }
export function AIFinancialBrief() { const { transactions } = useFinance(); const { income, expenses } = totals(transactions); const rate = income ? Math.round((expenses / income) * 100) : 0; return <section className="rounded-[22px] border border-[#B8D0C8] bg-soft-sage p-4"><div className="flex gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-green text-white"><Sparkles size={18}/></span><div><div className="flex items-center gap-2"><p className="text-[11px] font-bold tracking-[.1em] text-green">MONEY SNAPSHOT</p><span className="rounded-full bg-white/70 px-2 py-0.5 text-[9px] font-semibold text-green">Local</span></div><p className="mt-2 text-[13px] leading-5 text-[#315A50]">You&apos;ve used {rate}% of the income you&apos;ve recorded this month. Keep an eye on your everyday spending.</p><Link href="/analytics" className="mt-2 flex min-h-7 items-center gap-1 text-xs font-semibold text-green">See breakdown <ChevronRight size={14}/></Link></div></div></section>; }
type OverviewPeriod = "week" | "month" | "year";
type ChartPoint = { label: string; amount: number };
const dateKey = (date: Date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`;

function flowForPeriod(transactions: ReturnType<typeof useFinance>["transactions"], period: OverviewPeriod, flow: "expense" | "income"): ChartPoint[] {
  const today = new Date();
  const expenseByDate = new Map<string, number>();
  transactions.filter((transaction) => transaction.type === flow).forEach((transaction) => expenseByDate.set(transaction.date, (expenseByDate.get(transaction.date) ?? 0) + transaction.amount));
  if (period === "week") return Array.from({ length: 7 }, (_, index) => { const date = new Date(today.getFullYear(), today.getMonth(), today.getDate() - 6 + index); return { label: date.toLocaleDateString("en-MY", { weekday: "narrow" }), amount: expenseByDate.get(dateKey(date)) ?? 0 }; });
  if (period === "month") { const firstDay = new Date(today.getFullYear(), today.getMonth(), 1); const weeks = Math.ceil((firstDay.getDay() + new Date(today.getFullYear(), today.getMonth() + 1, 0).getDate()) / 7); const amounts = Array.from({ length: weeks }, () => 0); transactions.filter((transaction) => transaction.type === flow).forEach((transaction) => { const date = new Date(`${transaction.date}T00:00:00`); if (date.getFullYear() === today.getFullYear() && date.getMonth() === today.getMonth()) amounts[Math.floor((date.getDate() - 1 + firstDay.getDay()) / 7)] += transaction.amount; }); return amounts.map((amount, index) => ({ label: `W${index + 1}`, amount })); }
  const amounts = Array.from({ length: 12 }, () => 0); const startMonth = new Date(today.getFullYear(), today.getMonth() - 11, 1); transactions.filter((transaction) => transaction.type === flow).forEach((transaction) => { const date = new Date(`${transaction.date}T00:00:00`); const difference = (date.getFullYear() - startMonth.getFullYear()) * 12 + date.getMonth() - startMonth.getMonth(); if (difference >= 0 && difference < 12) amounts[difference] += transaction.amount; }); return amounts.map((amount, index) => ({ label: new Date(startMonth.getFullYear(), startMonth.getMonth() + index, 1).toLocaleDateString("en-MY", { month: "short" }).slice(0, 1), amount }));
}

export function MonthlyOverview() {
  const { transactions } = useFinance();
  const [period, setPeriod] = useState<OverviewPeriod>("month");
  const [flow, setFlow] = useState<"expense" | "income">("expense");
  const points = useMemo(() => flowForPeriod(transactions, period, flow), [transactions, period, flow]);
  const [selectedIndex, setSelectedIndex] = useState(Math.max(0, points.length - 1));
  const selected = points[Math.min(selectedIndex, points.length - 1)] ?? { label: "—", amount: 0 };
  const maximum = Math.max(...points.map((point) => point.amount), 1);
  const labels = { week: "Weekly", month: "Monthly", year: "Yearly" };
  const flowLabel = flow === "expense" ? "Expenses" : "Income";
  return <section className="rounded-[24px] bg-forest p-4 text-white shadow-lg shadow-forest/15"><div className="flex items-start justify-between gap-3"><div><p className="font-display text-base font-semibold">{labels[period]} overview</p><p className="mt-0.5 text-xs text-white/55">Your {flowLabel.toLowerCase()} activity</p></div><div className="rounded-full bg-white/10 p-1"><div className="flex"><button type="button" onClick={() => { setPeriod("week"); setSelectedIndex(6); }} className={`rounded-full px-2.5 py-1 text-[10px] font-semibold transition ${period === "week" ? "bg-white text-ink shadow-sm" : "text-white/60"}`}>Week</button><button type="button" onClick={() => { setPeriod("month"); setSelectedIndex(4); }} className={`rounded-full px-2.5 py-1 text-[10px] font-semibold transition ${period === "month" ? "bg-white text-ink shadow-sm" : "text-white/60"}`}>Month</button><button type="button" onClick={() => { setPeriod("year"); setSelectedIndex(11); }} className={`rounded-full px-2.5 py-1 text-[10px] font-semibold transition ${period === "year" ? "bg-white text-ink shadow-sm" : "text-white/60"}`}>Year</button></div></div></div><div className="mt-4 grid grid-cols-2 rounded-xl bg-white/10 p-1"><button type="button" onClick={() => setFlow("expense")} className={`min-h-8 rounded-lg text-[11px] font-semibold transition ${flow === "expense" ? "bg-white text-ink shadow-sm" : "text-white/55"}`}>Expenses</button><button type="button" onClick={() => setFlow("income")} className={`min-h-8 rounded-lg text-[11px] font-semibold transition ${flow === "income" ? "bg-white text-ink shadow-sm" : "text-white/55"}`}>Income</button></div><div className="mt-4 rounded-2xl bg-white/10 px-3 py-2.5"><div className="flex items-end justify-between"><span className="text-[11px] font-medium text-white/60">{selected.label}</span><span className="font-finance text-sm font-semibold">{money(selected.amount)}</span></div><div className="mt-4 flex h-28 items-end gap-1.5">{points.map((point, index) => <button key={`${point.label}-${index}`} type="button" onClick={() => setSelectedIndex(index)} aria-label={`${point.label}: ${money(point.amount)}`} className="group flex h-full min-w-0 flex-1 flex-col justify-end"><span className={`w-full rounded-t-md transition-all duration-300 ${selectedIndex === index ? "bg-sage shadow-[0_0_16px_rgba(143,175,165,.55)]" : "bg-white/25 group-hover:bg-white/45"}`} style={{ height: `${point.amount ? Math.max(12, Math.round((point.amount / maximum) * 100)) : 5}%` }} /><span className={`mt-2 text-center text-[9px] font-medium ${selectedIndex === index ? "text-sage" : "text-white/45"}`}>{point.label}</span></button>)}</div></div><div className="mt-3 flex items-center justify-between text-xs"><span className="text-white/55">Tap a bar for details</span><span className="font-medium text-sage">{flowLabel}</span></div></section>;
}
const categoryStyle: Record<string, string> = { Groceries: "bg-[#F5ECE5] text-[#8D593E]", Transport: "bg-[#E9F0E9] text-[#35704D]", Income: "bg-soft-sage text-green", "Food & drink": "bg-[#F7EAF0] text-[#97506D]", Subscriptions: "bg-[#E7EFF7] text-[#42617B]" };
export function RecentTransactions() { const { transactions } = useFinance(); return <section><div className="flex items-center justify-between"><div><p className="font-display text-base font-semibold text-ink">Recent transactions</p><p className="mt-0.5 text-xs text-muted">Your latest activity</p></div><Link href="/transactions" className="flex min-h-10 items-center gap-0.5 text-xs font-semibold text-green">View all <ChevronRight size={15}/></Link></div><div className="mt-3 divide-y divide-line overflow-hidden rounded-[22px] border border-line bg-white">{transactions.slice(0, 3).map((transaction) => <div key={transaction.id} className="flex items-center gap-3 p-3.5"><span className={`grid h-9 w-9 place-items-center rounded-xl ${categoryStyle[transaction.category] ?? "bg-canvas text-muted"}`}><CreditCard size={17}/></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-ink">{transaction.name}</p><p className="mt-0.5 text-xs text-muted">{transaction.category} · {new Date(`${transaction.date}T00:00:00`).toLocaleDateString("en-MY", { day: "numeric", month: "short" })}</p></div><p className={`font-finance text-xs font-medium ${transaction.type === "income" ? "text-green" : "text-ink"}`}>{transaction.type === "income" ? "+ " : "− "}{money(transaction.amount)}</p></div>)}</div></section>; }
export function BudgetAlert() { const { transactions, budgets } = useFinance(); const spending = transactions.filter((item) => item.type === "expense").reduce<Record<string, number>>((all, item) => ({ ...all, [item.category]: (all[item.category] ?? 0) + item.amount }), {}); const alert = budgets.map((budget) => ({ ...budget, used: spending[budget.category] ?? 0 })).find((budget) => budget.used >= budget.limit * 0.8); if (!alert) return null; const over = alert.used > alert.limit; return <Link href="/analytics" className={`block rounded-[20px] border p-4 ${over ? "border-[#E8BBB0] bg-[#FBEDE9]" : "border-[#B8D0C8] bg-soft-sage"}`}><p className={`text-xs font-bold tracking-[.08em] ${over ? "text-[#A33F2D]" : "text-green"}`}>{over ? "BUDGET ALERT" : "BUDGET CHECK-IN"}</p><p className="mt-1 text-sm text-ink">{over ? `${alert.category} is over its RM ${alert.limit.toFixed(0)} budget.` : `${alert.category} has reached ${Math.round((alert.used / alert.limit) * 100)}% of its monthly budget.`}</p></Link>; }
