"use client";

import type { User } from "@supabase/supabase-js";
import { createContext, useContext, useEffect, useMemo, useState } from "react";
import { supabase } from "@/lib/supabase";

export type Transaction = { id: string; name: string; category: string; amount: number; type: "income" | "expense"; date: string };
export type Budget = { id: string; category: string; limit: number };
export type PersonalGoal = { id: string; name: string; amount: number };
type NewTransaction = Omit<Transaction, "id">;
type FinanceState = { user: User | null; loading: boolean; transactions: Transaction[]; budgets: Budget[]; goals: PersonalGoal[]; savingsGoal: number; addTransaction: (transaction: NewTransaction) => Promise<void>; updateTransaction: (id: string, transaction: NewTransaction) => Promise<void>; deleteTransaction: (id: string) => Promise<void>; setBudget: (category: string, limit: number) => Promise<void>; setSavingsGoal: (goal: number) => Promise<void>; addGoal: (goal: Omit<PersonalGoal, "id">) => Promise<void>; signOut: () => Promise<void>; refresh: () => Promise<void>; };
const FinanceContext = createContext<FinanceState | null>(null);
const mapTransaction = (item: { id: string; name: string; category: string; amount: number | string; type: string; transaction_date: string }): Transaction => ({ id: item.id, name: item.name, category: item.category, amount: Number(item.amount), type: item.type as "income" | "expense", date: item.transaction_date });
const mapGoal = (item: { id: string; name: string; amount: number | string }): PersonalGoal => ({ id: item.id, name: item.name, amount: Number(item.amount) });

export function FinanceProvider({ children }: { children: React.ReactNode }) {
  const [user, setUser] = useState<User | null>(null); const [loading, setLoading] = useState(true); const [transactions, setTransactions] = useState<Transaction[]>([]); const [budgets, setBudgets] = useState<Budget[]>([]); const [goals, setGoals] = useState<PersonalGoal[]>([]); const [savingsGoal, setSavingsGoalState] = useState(1500);
  async function refresh() { if (!user) return; const [transactionResult, goalResult, budgetResult, personalGoalResult] = await Promise.all([supabase.from("transactions").select("id,name,category,amount,type,transaction_date").order("transaction_date", { ascending: false }).order("created_at", { ascending: false }), supabase.from("goals").select("savings_goal").maybeSingle(), supabase.from("budgets").select("id,category,monthly_limit").order("category"), supabase.from("personal_goals").select("id,name,amount").order("created_at")]); if (transactionResult.error) throw transactionResult.error; if (goalResult.error) throw goalResult.error; if (budgetResult.error) throw budgetResult.error; if (personalGoalResult.error) throw personalGoalResult.error; setTransactions((transactionResult.data ?? []).map(mapTransaction)); setSavingsGoalState(Number(goalResult.data?.savings_goal ?? 1500)); setBudgets((budgetResult.data ?? []).map((item) => ({ id: item.id, category: item.category, limit: Number(item.monthly_limit) }))); setGoals((personalGoalResult.data ?? []).map(mapGoal)); }
  useEffect(() => { let active = true; supabase.auth.getSession().then(({ data: { session } }) => { if (active) { setUser(session?.user ?? null); setLoading(false); } }); const { data: { subscription } } = supabase.auth.onAuthStateChange((_event, session) => { setUser(session?.user ?? null); setLoading(false); }); return () => { active = false; subscription.unsubscribe(); }; }, []);
  useEffect(() => { if (user) refresh().catch(console.error); else { setTransactions([]); setBudgets([]); setGoals([]); setSavingsGoalState(1500); } }, [user]);
  const value = useMemo(() => ({ user, loading, transactions, budgets, goals, savingsGoal, refresh, signOut: async () => { await supabase.auth.signOut(); }, addTransaction: async (transaction: NewTransaction) => { const { data, error } = await supabase.from("transactions").insert({ name: transaction.name, category: transaction.category, amount: transaction.amount, type: transaction.type, transaction_date: transaction.date }).select("id,name,category,amount,type,transaction_date").single(); if (error) throw error; setTransactions((current) => [mapTransaction(data), ...current]); }, updateTransaction: async (id: string, transaction: NewTransaction) => { const { data, error } = await supabase.from("transactions").update({ name: transaction.name, category: transaction.category, amount: transaction.amount, type: transaction.type, transaction_date: transaction.date }).eq("id", id).select("id,name,category,amount,type,transaction_date").single(); if (error) throw error; setTransactions((current) => current.map((item) => item.id === id ? mapTransaction(data) : item)); }, deleteTransaction: async (id: string) => { const { error } = await supabase.from("transactions").delete().eq("id", id); if (error) throw error; setTransactions((current) => current.filter((item) => item.id !== id)); }, setBudget: async (category: string, limit: number) => { const { data, error } = await supabase.from("budgets").upsert({ user_id: user?.id, category, monthly_limit: limit, updated_at: new Date().toISOString() }, { onConflict: "user_id,category" }).select("id,category,monthly_limit").single(); if (error) throw error; setBudgets((current) => [...current.filter((item) => item.category !== category), { id: data.id, category: data.category, limit: Number(data.monthly_limit) }].sort((a, b) => a.category.localeCompare(b.category))); }, setSavingsGoal: async (goal: number) => { setSavingsGoalState(goal); const { error } = await supabase.from("goals").upsert({ user_id: user?.id, savings_goal: goal, updated_at: new Date().toISOString() }, { onConflict: "user_id" }); if (error) throw error; }, addGoal: async (goal: Omit<PersonalGoal, "id">) => { const { data, error } = await supabase.from("personal_goals").insert(goal).select("id,name,amount").single(); if (error) throw error; setGoals((current) => [...current, mapGoal(data)]); } }), [user, loading, transactions, budgets, goals, savingsGoal]);
  return <FinanceContext.Provider value={value}>{children}</FinanceContext.Provider>;
}
export function useFinance() { const state = useContext(FinanceContext); if (!state) throw new Error("useFinance must be used within FinanceProvider"); return state; }
export const money = (amount: number) => new Intl.NumberFormat("en-MY", { style: "currency", currency: "MYR", minimumFractionDigits: 2 }).format(amount).replace("MYR", "RM");
export function totals(transactions: Transaction[]) { const income = transactions.filter((t) => t.type === "income").reduce((sum, t) => sum + t.amount, 0); const expenses = transactions.filter((t) => t.type === "expense").reduce((sum, t) => sum + t.amount, 0); return { income, expenses, balance: income - expenses, saved: Math.max(0, income - expenses) }; }
