"use client";
import Link from "next/link";
import { BarChart3, CirclePlus, House, ReceiptText, Target } from "lucide-react";
import { usePathname } from "next/navigation";

const nav = [{ href: "/", label: "Home", icon: House }, { href: "/transactions", label: "Transactions", icon: ReceiptText }, { href: "/analytics", label: "Analytics", icon: BarChart3 }, { href: "/goals", label: "Goals", icon: Target }];
function NavItem({ item, compact = false }: { item: typeof nav[number]; compact?: boolean }) { const path = usePathname(); const active = path === item.href; const Icon = item.icon; return <Link href={item.href} className={compact ? `flex min-w-0 flex-1 flex-col items-center gap-1 py-1 text-[10px] font-medium ${active ? "text-green" : "text-muted"}` : `flex min-h-12 items-center gap-3 rounded-xl px-3 text-sm font-semibold ${active ? "bg-soft-sage text-green" : "text-muted hover:bg-white hover:text-ink"}`}><Icon size={compact ? 20 : 19} strokeWidth={active ? 2.4 : 1.8}/><span className="truncate">{item.label}</span></Link>; }
export function MobileBottomNav() { return <nav aria-label="Main navigation" className="fixed inset-x-0 bottom-0 z-30 px-4 pb-[max(14px,env(safe-area-inset-bottom))] md:hidden"><div className="mx-auto flex max-w-md items-end rounded-[24px] border border-white/15 bg-[#0A362D]/95 px-2 py-2 shadow-2xl shadow-black/30 backdrop-blur"><NavItem item={nav[0]} compact /><NavItem item={nav[1]} compact /><Link href="/add" aria-label="Add transaction" className="-mt-7 grid h-14 w-14 shrink-0 place-items-center rounded-full border-[5px] border-[#0B4035] bg-[#45E4C1] text-[#0A362D] shadow-lg shadow-black/30"><CirclePlus size={27}/></Link><NavItem item={nav[2]} compact /><NavItem item={nav[3]} compact /></div></nav>; }
export function DesktopSidebar() { return <aside className="sticky top-0 hidden h-dvh w-64 shrink-0 flex-col border-r border-line bg-white px-4 py-7 md:flex"><Link href="/" className="mb-10 flex items-center gap-3 px-2"><span className="grid h-9 w-9 place-items-center rounded-xl bg-forest font-display text-lg font-bold text-white">B</span><span className="font-display text-xl font-semibold text-forest">bao</span></Link><nav aria-label="Main navigation" className="space-y-1">{nav.map((item) => <NavItem key={item.href} item={item}/>)}</nav><Link href="/add" className="mt-8 flex min-h-12 items-center justify-center gap-2 rounded-xl bg-forest px-4 text-sm font-semibold text-white"><CirclePlus size={19}/> Add transaction</Link><div className="mt-auto rounded-2xl bg-soft-sage p-4"><p className="font-display text-sm font-semibold text-green">A little progress</p><p className="mt-1 text-xs leading-5 text-muted">You&apos;re on track to reach this month&apos;s savings goal.</p></div></aside>; }
